export const STRENGTHS_LIST: string[] = [
  'Adventurous',
  'Ambition',
  'Artistic Ability',
  'Assertiveness',
  'Athleticism',
  'Bravery',
  'Common Sense',
  'Confidence',
  'Cooperation',
  'Creativity',
  'Curiosity',
  'Discipline',
  'Empathy',
  'Enthusiasm',
  'Fairness',
  'Flexibility',
  'Forgiveness',
  'Gratitude',
  'Honesty',
  'Humor',
  'Independence',
  'Intelligence',
  'Kindness',
  'Leadership',
  'Logic',
  'Love',
  'Love of Learning',
  'Mindedness',
  'Modesty',
  'Optimism',
  'Patience',
  'Persistence',
  'Self-Control',
  'Social Awareness',
  'Spirituality',
  'Wisdom',
];
